version: '3.3'
services:
  eipm-calculator:
    image: sc-registry.fredhutch.org/eipm-calculator:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.eipm-calculator.rule=Host(`eipm.fredhutch.org`)"
        - "traefik.http.routers.eipm-calculator-secured.rule=Host(`eipm.fredhutch.org`)"
        - "traefik.http.routers.eipm-calculator.entrypoints=web,web-secured"
        - "traefik.http.services.eipm-calculator.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.eipm-calculator.tls=true"

networks:
  sc-swarm-net:
    external: true